### ISSUE TITLE
Home Activity

### ISSUE THREAD

**Issue by nockzblack** [nockzblack/devxican_mobile#4]
- News API (@nockzblack )
- Recent Post : show RecyclerView on recent posts made by followed people and on click start post activity intent (@lchrios )

**Comment by lchrios** [comment]
- News API (@nockzblack )
- Recent Post :  show RecyclerView on recent posts made by followed people and on click start post activity intent (@lchrios )

**Comment by nockzblack** [comment]
missing: Recent Post : show RecyclerView on recent posts made by followed people and on click start post activity intent
